Update dependabot-auto-approve.yml

diff --git a/.github/workflows/dependabot-auto-approve.yml b/.github/workflows/dependabot-auto-approve.yml
--- a/.github/workflows/dependabot-auto-approve.yml
+++ b/.github/workflows/dependabot-auto-approve.yml
@@ -16,6 +16,15 @@ jobs:
     runs-on: ubuntu-latest
     if: github.actor == 'dependabot[bot]'
     steps:
+      - name: Debug Secrets
+        run: |
+          if [ -z "${{ secrets.MYTOKEN }}" ]; then
+            echo "❌ MYTOKEN is missing!"
+            exit 1
+          else
+            echo "✅ MYTOKEN is available."
+          fi
+
       - name: Dependabot Auto Merge
         uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
         with:
